### ISSUE TITLE
Where are all your issues?

### ISSUE THREAD

**Issue by ritjoe** [skimboarder/hfoss-finalproject#1]
So, one of the points of this project is for students to demonstrate a practical grasp of using collaborative development tools.

It's possible to develop collaboratively without using Github issues and pull requests, but usually doing without Github (or other forge) project tools is an intermediate or advanced approach. If this team is using other venues for coordinating their work then that would be appropriate to note in a CONTRIBUTING.md file or similar in the repo.

If not, the team should probably begin using issues and a PR based workflow within Github. Create issues for development tasks and track progress on those tasks through each relevant issue.

**Comment by skimboarder** [comment]
Thanks for pointing this out!

Issues have now been made for pending tasks.
